name: conditions yml
on:
  workflow_dispatch:
jobs:
  check-conditions:
    runs-on: ubuntu-latest
    steps:
      - if: github.ref == 'refs/heads/main'
        id: step1
        name: Print on only main
        run: echo "hello"
      - if: steps.step1.status != 'success'
        name: running if previos failed
        run: echo "Previous step failed"
       
      - name: print always
        run: echo "always"