name: using composite action

on: 
  push:

jobs:

  greet:
    runs-on: ubuntu-latest
   
    steps:
      
      - name: checkout
        uses: actions/checkout@v4
        
      - name: greet & setup
        uses: ./.github/actions/setup-and-greet
        with:
          name: 'Afroz'
