name: passing jobs output
on: 
  workflow_dispatch:
jobs:
  set:
    outputs: 
      date_output: ${{ steps.get_date.outputs.date }}
    runs-on: ubuntu-latest
    steps:
      - id: get_date
        name: set output to today's date
        run: echo "date=$(date)" >> $GITHUB_OUTPUT
  get:
    runs-on: ubuntu-latest
    needs: set
    steps:
      - name: Get output from previous job
        run: ${{ needs.set.outputs.date }}
    