name: multi-job
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Building app
        run: echo "Building the app"
  test:
    depends_on: build
    runs-on: ubuntu-latest
    steps:
      - name: Running test
        run: echo "Running tests"
  deploy:
    depends_on: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploying
        run: echo "Deploying"