name: smart triggers

on:
  push:
    paths:
      - 'src/**'
      - 'app/**'

jobs:
 
  print:
    runs-on: ubuntu-latest

    steps:
      
      - name: print
        run: |
          Files=$(git diff --name-only origin/${{ github.ref_name }} HEAD)
          for file in $Files; do
            echo "$file"
          done